export const mediaFranchises = [
    "power rangers",
	"pokemon",
	"dark souls",
	"mad max",
	"high school musical",
	"my hero academia",
	"dragon ball z",
	"neopets",
	"yugioh",
	"digimon",
	"hello kitty",
	"animal crossing",
	"doom",
	"warhammer 40k",
	"my little pony",
	"rambo",
	"hunger games",
	"dc heroes",
	"marvel heroes",
	"transformers",
	"sailor moon",
	"dc villains",
	"marvel villains",
	"ninja gaidan",
	"final fantasy",
	"robocop",
	"star wars",
	"star trek",
	"sherlock holmes",
	"dracula",
	"munsters",
	"the adams family",
	"looney toons",
	"harry potter",
	"disney",
	"mario bros",
	"kirby",
	"metal gear solid",
	"harry potter",
	"lord of the rings",
	"peanuts",
	"teenage mutant ninja turtle",
	"one piece",
	"james bond",
	"league of legends",
	"street fighter",
	"sesame street",
	"sonic the hedgehog",
	"xmen",
	"naruto",
	"zelda",
	"godzilla and monsters",
	"avatar the last airbender",
	"powerpuff girls",
	"god of war",
	"samurai jack",
	"dexters lab",
	"indiana jones",
	"tomb raider",
	"halo",
	"warcraft",
	"overwatch",
	"kung fu panda",
	"pirates of the carribean",
	"ben 10",
	"twilight",
	"fate/stay night",
	"mortal kombat",
	"katamari damacy",
	"kamen rider",
	"inuyasha",
	"steven universe",
	"adventure time",
	"dexters lab",
	"attack on titan",
	"fullmetal alchemist",
	"evangelion",
	"stranger things",
	"breaking bad",
	"left4dead",
	"evil dead",
	"devil may cry",
	"persona (shin megami tensei)",
	"king of fighters",
	"tekken",
	"fire emblem",
	"banjo and kazooie",
	"kingdom hearts",
	"pixar",
	"minecraft",
	"dragon quest",
	"monster hunter",
	"spongebob",
	"dungeons and dragons",
	"elder scrolls",
	"megaman",
	"castlevania",
	"fast and the furious",
	"neir automata",
	"xenoblade chronicles",
	"rick and morty",
	"flintstones",
	"witcher"
]